meeting_planner/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('meetings.urls'))

]

meetings/urls.py
from django.urls import path
from . import views

app_name = 'meetings'

urlpatterns = [

    path('<int:id>',views.detail,name="detail"),
    path('rooms',views.room,name="rooms"),
    path('new', views.new, name="new"),
    path('', views.welcome, name="welcome"),


]

meetings/models.py
from django.db import models
from datetime import time
# Create your models here.


class Room(models.Model):
    name=models.CharField(max_length=50)
    floor=models.IntegerField()
    room_number =models.IntegerField( )

    def __str__(self):
        return f"{self.name} : room  {self.room_number} on floor {self.floor} "

class Meeting(models.Model):
    title=models.CharField(max_length=200)
    date=models.DateField()
    start_time = models.TimeField(default=time(9))
    duration = models.IntegerField(default=1)
    room = models.ForeignKey(Room,on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.title} at {self.start_time} on {self.date}  "

meetings/forms.py
from datetime import date

from django.forms import ModelForm, DateInput, TimeInput, TextInput, IntegerField
from django.core.exceptions import ValidationError

from .models import Meeting


class MeetingForm(ModelForm):
    class Meta:
        model = Meeting
        fields = '__all__'
        widgets = {
            'title': TextInput(attrs={"placeholder":"Create a title"}),
            'date': DateInput( attrs={"type": "date"}),
            'start': TimeInput(attrs={"type": "time"}),
            'duration': TextInput(attrs={"type": "number","min":"1", "max":"4"})
        }

    def clean_date(self):
        d = self.cleaned_data.get("date")
        if d < date.today():
            raise ValidationError("Meetings cannot be in the past")
        return d

meetings/views.py
from django.shortcuts import render,get_object_or_404,redirect,reverse
from django.forms import modelform_factory

from .models import Meeting,Room
from .forms import MeetingForm
# Create your views here.

def welcome(request):
    return render(request,"meetings/welcome.html",{
        "rooms":Room.objects.all(),
        "meetings": Meeting.objects.all()

    })

def detail (request,id):
    meeting=get_object_or_404(Meeting,pk=id)
    return render (request,"meetings/detail.html", {"meeting" : meeting})

def room(request):
   # room=get_object_or_404(Room.name)
    return render(request,"meetings/rooms.html",
                  {"rooms":Room.objects.all()}
                   )

#MeetingForm=modelform_factory(Meeting,exclude=[])

def new(request):
    if request.method =="POST":
        form=MeetingForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    else:
        form=MeetingForm()
    return render (request, "meetings/new.html", {"form": form})

meetings/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css"
          href="{% static 'meetings/css/style.css' %}">
</head>
<body>
    <img src="{% static 'meetings/img/meeting.png' %}" alt="Logo" height="250px">
        {% block content %}
        {% endblock %}
</body>
</html>

meetings/templates/meetings/detail.html
{% extends "base.html" %}
 {% block title %} Details {% endblock %}
{% block content %}
<h1>{{meeting.title}}</h1>
<p>
    This meeting has been scheduled on {{meeting.date}}, at
    {{meeting.start_time}} in <strong> {{meeting.room}}</strong>
</p>
<a href="{% url 'meetings:welcome'  %}">Home</a>

 {% endblock %}

meetings/templates/meetings/new.html
{% extends "base.html" %}
{% block title %} New Meeting {% endblock%}
{% block content %}

<h1> Plan a new meeting</h1>
<form method="post">
    <table>
        {{form}}
    </table>
    <button type="submit">Create </button>
    {% csrf_token %}
</form>

<a href="{% url 'meetings:welcome'  %}">Home</a>
{% endblock%}

meetings/templates/meetings/rooms.html
{% extends "base.html" %}
 {% block title %} Rooms {% endblock %}
{% block content %}
<h1>Rooms Of Meeting :</h1>
    <ul>
        {% for x in rooms %}
        <li>
            <strong>{{x}}</strong>
        </li>
        {% endfor %}

    </ul>

<a href="{% url 'meetings:welcome'  %}">Home</a>
{% endblock %}

meetings/templates/meetings/welcome.html
{% extends "base.html" %}

{% block title %} Welcome {% endblock%}

{% block content %}
<h1> Welcome to the Meeting WebSite !</h1>

<h2>liste of Meetings</h2>
         <ul>
               {% for x in meetings %}
                    <li>
                          <a href="{% url 'meetings:detail'  x.id %}">
                                  {{x.title}}
                          </a>
                     </li>
               {% endfor %}
         </ul>


    <p>
         <a href="{% url 'meetings:rooms'  %}">List of Rooms</a>
    </p>
    <p>
        <a href="{% url 'meetings:new'  %}">add  new meeting</a>
    </p>


{% endblock%}